### ISSUE TITLE
rake db:migrate errors out referencing /tmp/mysql.sock

### ISSUE THREAD

**Issue by anothermh** [collectiveidea/delayed_job_active_record#108]
I am trying to use delayed_job_active_record using Ruby 2.2.1 and Rails 4.2.1. I followed these steps:

```
gem 'delayed_job'
gem 'delayed_job_active_record'
```

...in the Gemfile. Then on the command line:

```
bundle install
rails g delayed_job:active_record
rake db:migrate
```

I get this output:

```
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/Users/message/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
/Users/message/.rvm/gems/ruby-2.2.1/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:913:in `initialize'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `new'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/message/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/message/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/message/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

When I remove the gems and run bundle install, rake db:migrate works fine. MySQL is NOT installed on this machine, and my database.yml file looks like this:

```
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB'] %>
  username: <%= ENV['U'] %>
  password: <%= ENV['P'] %>
  host: <%= ENV['H'] %>
  port: <%= ENV['PORT'] %>

production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['PDB'] %>
  username: <%= ENV['PU'] %>
  password: <%= ENV['PP'] %>
  host: <%= ENV['PH'] %>
  port: <%= ENV['PPORT'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3
```

I can't figure out for the life of me why rake db:migrate thinks it should be looking for MySQL at /tmp/mysql.sock.

Same thing happens when I run:

```
rake db:migrate RAILS_ENV="development"
```

or

```
rake db:migrate RAILS_ENV="production"
```

**Comment by betamatt** [comment]
This is clearly a configuration issue with your app. Off hand, I'd guess you're not picking up your ENV vars are not populated the way you think.

**Comment by anothermh** [comment]
You're right. The ENV vars, although picked up and used properly on every other rake db:migrate, for some reason would cause it to error out here. I set them to static values and can confirm it's working now. Hopefully if someone else gets this issue they'll find this solution.
