### ISSUE TITLE
can't convert String into time interval starting worker heroku

### ISSUE THREAD

**Issue by raldred** [collectiveidea/delayed_job_active_record#116]
I'm getting an issue on postgres on heroku where a job cannot be cleared.
The worker crashes with the following error when starting up:

`can't convert String into time interval`

	heroku[worker.1]: State changed from crashed to starting
	heroku[worker.1]: Starting process with command `bundle exec rake jobs:work`
	heroku[worker.1]: State changed from starting to up
	app[worker.1]:   SQL (0.5ms)  UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1  [["locked_by", "host:4e2ca0ce-f20e-49ec-868e-46641d3d6e08 pid:3"]]
	app[worker.1]: rake aborted!
	app[worker.1]: TypeError: can't convert String into time interval
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:180:in `sleep'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:180:in `block (2 levels) in start'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `call'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start'
	app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
	app[worker.1]: Tasks: TOP => jobs:work
	app[worker.1]: (See full trace by running task with --trace)
	app[worker.1]: [Worker(host:4e2ca0ce-f20e-49ec-868e-46641d3d6e08 pid:3)] Starting job worker
	app[worker.1]: 2015-11-23T23:46:05+0000: [Worker(host:4e2ca0ce-f20e-49ec-868e-46641d3d6e08 pid:3)] Starting job worker
	app[worker.1]:   Delayed::Backend::ActiveRecord::Job Load (1.3ms)  UPDATE "delayed_jobs" SET locked_at = '2015-11-23 23:46:05.412865', locked_by = 'host:4e2ca0ce-f20e-49ec-868e-46641d3d6e08 pid:3' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-11-23 23:46:05.385111' AND (locked_at IS NULL OR locked_at < '2015-11-23 19:46:05.385138') OR locked_by = 'host:4e2ca0ce-f20e-49ec-868e-46641d3d6e08 pid:3') AND failed_at IS NULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
	heroku[worker.1]: Process exited with status 1
	heroku[worker.1]: State changed from up to crashed

**Comment by raldred** [comment]
wrong repo sorry
