### ISSUE TITLE
Urgent - issue with Ruby 2.5.0

### ISSUE THREAD

**Issue by mesutcan** [collectiveidea/delayed_job_active_record#150]
I upgraded to Ruby 2.5.0 but when I am trying to run my app, I get an error saying "There was an error while trying to load the gem 'delayed_job_active_record'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `yaml_as' for ActiveRecord::Base:Class":

```
  /Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'delayed_job_active_record'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
Backtrace for gem load error is:
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:2:in `<top (required)>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:66:in `backend='
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/delayed_job_active_record-4.1.2/lib/delayed_job_active_record.rb:5:in `<top (required)>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/milhaner/Desktop/projects/dailyJournal/config/application.rb:8:in `<top (required)>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `require'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `block in server'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
/Users/milhaner/Desktop/projects/dailyJournal/bin/rails:8:in `require'
/Users/milhaner/Desktop/projects/dailyJournal/bin/rails:8:in `<top (required)>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/client/rails.rb:28:in `load'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/client/rails.rb:28:in `call'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/client/command.rb:7:in `call'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/client.rb:28:in `run'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/bin/spring:49:in `<top (required)>'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/binstub.rb:11:in `load'
/Users/milhaner/.rvm/gems/ruby-2.5.0/gems/spring-1.4.4/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/milhaner/Desktop/projects/dailyJournal/bin/spring:16:in `require'
/Users/milhaner/Desktop/projects/dailyJournal/bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:

```

It seems delayed_job already fixed this: https://github.com/rails/rails/issues/30522
Could you also please fix it for delayed_job_active_record? Thanks!

**Comment by albus522** [comment]
You need to install the new gem. This isn't a DJ ActiveRecord issue.

**Comment by mesutcan** [comment]
@albus522 which new gem? Thanks!

**Comment by rdunlop** [comment]
@mesutcan Delayed-job 4.1.4 supports/fixes this (see https://github.com/collectiveidea/delayed_job/blob/master/CHANGELOG.md#414---2017-12-29)

**Comment by mesutcan** [comment]
@rdunlop thanks but I am using delayed_job_active_record. Can I just use delayed_job instead of delayed_job_active_record?

**Comment by rdunlop** [comment]
@mesutcan `delayed_job_active_record` has `delayed_job` as a dependency.

So, just running `bundle update delayed_job` in your project root should enable you to update the just that one gem. This won't result in installing `delayed_job` anew...since it's already there.

You'll see the change in your `Gemfile.lock`

For reference, the dependencies can be seen in the following ways:
1) you have in your backtrace a call to `delayed_job-4.1.3`
2) the gemspec states such (https://github.com/collectiveidea/delayed_job_active_record/blob/master/delayed_job_active_record.gemspec#L3)
3) your Gemfile.lock will show the dependencies under `delayed_job_active_record`
4) https://rubygems.org/gems/delayed_job_active_record lists the dependencies (delayed_job, and activerecord)
