### ISSUE TITLE
undefined method `clear_all_connections!' when running ./bin/delayed_job

### ISSUE THREAD

**Issue by lcjury** [collectiveidea/delayed_job_active_record#235]
I'm trying to use delayed_job_active_record on the new Rails version and I'm getting the following error:

```
/home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `clear_all_connections!' for ActiveRecord::Base:Class (NoMethodError)
Did you mean?  clear_validators!
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job_active_record-4.1.9/lib/delayed/backend/active_record.rb:67:in `before_fork'
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job-4.1.12/lib/delayed/worker.rb:92:in `before_fork'
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job-4.1.12/lib/delayed/command.rb:122:in `run_process'
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job-4.1.12/lib/delayed/command.rb:104:in `block in daemonize'
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job-4.1.12/lib/delayed/command.rb:102:in `times'
        from /home/vscode/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/delayed_job-4.1.12/lib/delayed/command.rb:102:in `daemonize'
        from ./bin/delayed_job:5:in `<main>'
```

This only happens with delayed_job_active_record 4.1.9, but 4.1.8 works as expected.
Reverting this PR https://github.com/collectiveidea/delayed_job_active_record/pull/226 on my local gem fixes the issue.

---

Here is my Gemfile.lock just in case (but it's just a Ruby 3.1.2 fresh Rails 7.2 install with 1 or 2 non-related gems)

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.2.0)
      actionpack (= 7.2.0)
      activesupport (= 7.2.0)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.2.0)
      actionpack (= 7.2.0)
      activejob (= 7.2.0)
      activerecord (= 7.2.0)
      activestorage (= 7.2.0)
      activesupport (= 7.2.0)
      mail (>= 2.8.0)
    actionmailer (7.2.0)
      actionpack (= 7.2.0)
      actionview (= 7.2.0)
      activejob (= 7.2.0)
      activesupport (= 7.2.0)
      mail (>= 2.8.0)
      rails-dom-testing (~> 2.2)
    actionpack (7.2.0)
      actionview (= 7.2.0)
      activesupport (= 7.2.0)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4, < 3.2)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
      useragent (~> 0.16)
    actiontext (7.2.0)
      actionpack (= 7.2.0)
      activerecord (= 7.2.0)
      activestorage (= 7.2.0)
      activesupport (= 7.2.0)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.2.0)
      activesupport (= 7.2.0)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (7.2.0)
      activesupport (= 7.2.0)
      globalid (>= 0.3.6)
    activemodel (7.2.0)
      activesupport (= 7.2.0)
    activerecord (7.2.0)
      activemodel (= 7.2.0)
      activesupport (= 7.2.0)
      timeout (>= 0.4.0)
    activestorage (7.2.0)
      actionpack (= 7.2.0)
      activejob (= 7.2.0)
      activerecord (= 7.2.0)
      activesupport (= 7.2.0)
      marcel (~> 1.0)
    activesupport (7.2.0)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.3.1)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      logger (>= 1.4.2)
      minitest (>= 5.1)
      securerandom (>= 0.3)
      tzinfo (~> 2.0, >= 2.0.5)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    ast (2.4.2)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    bindex (0.8.1)
    bootsnap (1.18.4)
      msgpack (~> 1.2)
    brakeman (6.1.2)
      racc
    builder (3.3.0)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.3.4)
    connection_pool (2.4.1)
    crass (1.0.6)
    daemons (1.4.1)
    date (3.3.4)
    debug (1.9.2)
      irb (~> 1.10)
      reline (>= 0.3.8)
    delayed_job (4.1.12)
      activesupport (>= 3.0, < 8.0)
    delayed_job_active_record (4.1.9)
      activerecord (>= 3.0, < 8.0)
      delayed_job (>= 3.0, < 5)
    drb (2.2.1)
    error_highlight (0.6.0)
    erubi (1.13.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    importmap-rails (2.0.1)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.12.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    json (2.7.2)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    language_server-protocol (3.17.0.3)
    logger (1.6.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    matrix (0.4.2)
    mini_mime (1.1.5)
    mini_portile2 (2.8.7)
    minitest (5.25.1)
    msgpack (1.7.2)
    net-imap (0.4.14)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
      net-protocol
    nio4r (2.7.3)
    nokogiri (1.16.7-aarch64-linux)
      racc (~> 1.4)
    nokogiri (1.16.7-arm-linux)
      racc (~> 1.4)
    nokogiri (1.16.7-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.16.7-x86-linux)
      racc (~> 1.4)
    nokogiri (1.16.7-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.16.7-x86_64-linux)
      racc (~> 1.4)
    parallel (1.26.3)
    parser (3.3.4.2)
      ast (~> 2.4.1)
      racc
    psych (5.1.2)
      stringio
    public_suffix (6.0.1)
    puma (6.4.2)
      nio4r (~> 2.0)
    racc (1.8.1)
    rack (3.1.7)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    rails (7.2.0)
      actioncable (= 7.2.0)
      actionmailbox (= 7.2.0)
      actionmailer (= 7.2.0)
      actionpack (= 7.2.0)
      actiontext (= 7.2.0)
      actionview (= 7.2.0)
      activejob (= 7.2.0)
      activemodel (= 7.2.0)
      activerecord (= 7.2.0)
      activestorage (= 7.2.0)
      activesupport (= 7.2.0)
      bundler (>= 1.15.0)
      railties (= 7.2.0)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.2.0)
      actionpack (= 7.2.0)
      activesupport (= 7.2.0)
      irb (~> 1.13)
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rainbow (3.1.1)
    rake (13.2.1)
    rdoc (6.7.0)
      psych (>= 4.0.0)
    regexp_parser (2.9.2)
    reline (0.5.9)
      io-console (~> 0.5)
    rexml (3.3.5)
      strscan
    rubocop (1.65.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.4, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.32.1)
      parser (>= 3.3.1.0)
    rubocop-minitest (0.35.1)
      rubocop (>= 1.61, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-performance (1.21.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.25.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails-omakase (1.0.0)
      rubocop
      rubocop-minitest
      rubocop-performance
      rubocop-rails
    ruby-progressbar (1.13.0)
    rubyzip (2.3.2)
    securerandom (0.3.1)
    selenium-webdriver (4.23.0)
      base64 (~> 0.2)
      logger (~> 1.4)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.5.2)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      sprockets (>= 3.0.0)
    sqlite3 (2.0.4)
      mini_portile2 (~> 2.8.0)
    sqlite3 (2.0.4-arm64-darwin)
    sqlite3 (2.0.4-x86_64-darwin)
    stimulus-rails (1.3.4)
      railties (>= 6.0.0)
    stringio (3.1.1)
    strscan (3.1.0)
    tailwindcss-rails (2.7.3)
      railties (>= 7.0.0)
    tailwindcss-rails (2.7.3-aarch64-linux)
      railties (>= 7.0.0)
    tailwindcss-rails (2.7.3-arm-linux)
      railties (>= 7.0.0)
    tailwindcss-rails (2.7.3-arm64-darwin)
      railties (>= 7.0.0)
    tailwindcss-rails (2.7.3-x86_64-darwin)
      railties (>= 7.0.0)
    tailwindcss-rails (2.7.3-x86_64-linux)
      railties (>= 7.0.0)
    thor (1.3.1)
    timeout (0.4.1)
    turbo-rails (2.0.6)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.5.0)
    useragent (0.16.10)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webrick (1.8.1)
    websocket (1.2.11)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.17)

PLATFORMS
  aarch64-linux
  aarch64-linux
  aarch64-linux-musl
  arm-linux
  arm-linux
  arm-linux-musl
  arm64-darwin
  x86-linux
  x86-linux
  x86-linux-musl
  x86_64-darwin
  x86_64-linux
  x86_64-linux
  x86_64-linux-musl

DEPENDENCIES
  bootsnap
  brakeman
  capybara
  daemons
  debug
  delayed_job_active_record
  error_highlight (>= 0.4.0)
  importmap-rails
  jbuilder
  kaminari
  puma (>= 5.0)
  rails (~> 7.2.0)
  rubocop-rails-omakase
  selenium-webdriver
  sprockets-rails
  sqlite3 (>= 1.4)
  stimulus-rails
  tailwindcss-rails (~> 2.7)
  turbo-rails
  tzinfo-data
  web-console

BUNDLED WITH
   2.5.10

```

**Comment by albus522** [comment]
New release pushed
